RETRIEVE = "retrieve"
GRADE_DOCUMENTS = "grade_documents"
GENERATE = "generate"
WEBSEARCH = "websearch"
DECIDE_VECTORSTORE = "decide_vectorstore"
DECIDE_LANGUAGE = "decide_language"
HUMAN_IN_LOOP = "human_in_loop"
INITIALIZE = "initialize"
